"""Add index on access token

Revision ID: f2f57cb2a5b0
Revises: cb232e6e9425
Create Date: 2025-02-24 21:33:31.076672

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2f57cb2a5b0"
down_revision: Union[str, None] = "fc5e2283de94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("oauth2token_access_token_key", "oauth2token", type_="unique")
    op.create_index(
        op.f("ix_oauth2token_access_token"), "oauth2token", ["access_token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth2token_access_token"), table_name="oauth2token")
    op.create_unique_constraint("oauth2token_access_token_key", "oauth2token", ["access_token"])
    # ### end Alembic commands ###
